### ISSUE TITLE
latest Docker image (version 1.0) fails with TypeError: crypto.randomUUID is not a function (works fine on 0.87.4)

### ISSUE THREAD

**Issue by gauravagnihotristla** [outline/outline#10480]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This is not related to configuring Outline

- [x] The issue is not related to self-hosting config

### Current Behavior

When using the current `1.0` i.e `outlinewiki/outline:1.0`, the web UI crashes immediately on load with the following error:
```
TypeError: crypto.randomUUID is not a function
at T5 (http://<domain>/static/assets/index.DIlMPz6e.js:170:11777)
at http://<domain>/static/assets/notifications.CdolPPzd.js:1:219
```

### Expected Behavior

The Outline web app should load normally.

### Steps To Reproduce

Steps to reproduce:
1. Deploy Outline using the current `docker pull outlinewiki/outline:1.0` image 
2. Access the instance in a browser
3. Observe frontend crash with the above error

### Environment

```markdown
- Outline: Outline 1.xx
- Browser: Chrome
```

### Anything else?

<img width="1004" height="366" alt="Image" src="https://github.com/user-attachments/assets/754fa0c6-f613-4c10-9d86-2e595108481c" />

**Comment by IamTaoChen** [comment]
I didn't meet this issue at `v1.0.0`

**Comment by RollsRoycewk** [comment]
I also have v0.86.1 working fine, but the v1.0.0 page has an error

<img width="897" height="417" alt="Image" src="https://github.com/user-attachments/assets/1ba5dc19-c214-4841-bac3-5c793487988d" />

TypeError: crypto.randomUUID is not a function
    at T5 (index.DIlMPz6e.js:170:11777)
    at notifications.CdolPPzd.js:1:218
 ErrorBoundary 
Object
error
: 
TypeError: crypto.randomUUID is not a function at T5 (http://xxx.xxx.xx.xx:3006/static/assets/index.DIlMPz6e.js:170:11777) at http://xxx.xxx.xx.xx:3006/static/assets/notifications.CdolPPzd.js:1:218
extra
: 
undefined
[[Prototype]]
: 
Object

**Comment by tommoor** [comment]
It sounds like you are using a very out of date browser – this API has been available in Chrome since [July 2021, v92](https://caniuse.com/mdn-api_crypto_randomuuid).

Could you confirm.

**Comment by RollsRoycewk** [comment]
Google Chrome
Version 141.0.7390.108 (Official Release) (64-bit)

**Comment by tommoor** [comment]
It looks like it's because you're not serving the app with SSL, the solution is to do so.

I wasn't aware of this restriction when switching to the new API, it's probably worth reverting that change as I'm not unsure how many people are not using https.

**Comment by ghost** [comment]
Since updating to v1.0.0 I have also an issue and could not access the wiki:
```
kl@http://192.168.178.2/static/assets/index.DIlMPz6e.js:10:9452
gl@http://192.168.178.2/static/assets/index.DIlMPz6e.js:10:949
ml@http://192.168.178.2/static/assets/index.DIlMPz6e.js:10:877
pl@http://192.168.178.2/static/assets/index.DIlMPz6e.js:10:731
il@http://192.168.178.2/static/assets/index.DIlMPz6e.js:8:10836
@http://192.168.178.2/static/assets/index.DIlMPz6e.js:6:38544
@http://192.168.178.2/static/assets/index.DIlMPz6e.js:2:58741
Na@http://192.168.178.2/static/assets/index.DIlMPz6e.js:6:38491
ne@http://192.168.178.2/static/assets/index.DIlMPz6e.js:2:57706
@http://192.168.178.2/static/assets/index.DIlMPz6e.js:2:56404
```

I#m using the latest version of Apple Safari and only in my local network without https. Is this also an SSL problem?

**Comment by tommoor** [comment]
Yes, same issue.<br>I will restore support for non-SSL in next patch
